/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.8
 * Generated at: 2014-06-09 18:24:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.io.BufferedReader;
import java.io.FileReader;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("UTF-8");
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>Bingle</title>\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/Bingle/css/button.css\" title=\"Style\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/Bingle/css/autoComplete.css\" title=\"Style\">\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write(".img {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("\tleft: 450px;\r\n");
      out.write("\ttop: 175px;\r\n");
      out.write("}\r\n");
      out.write(".keywards {\r\n");
      out.write("    width: 605px;\r\n");
      out.write("    height: 32px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    line-height: 22px;\r\n");
      out.write("    font-family: arial;\r\n");
      out.write("    margin: 5px 0px 0px 7px;\r\n");
      out.write("    background: none repeat scroll 0% 0% #FFF;\r\n");
      out.write("    outline: 0px none;\r\n");
      out.write("}\r\n");
      out.write(".button {\r\n");
      out.write("    width: 95px;\r\n");
      out.write("    height: 29px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    background-color: #F2F2F2;\r\n");
      out.write("    border-style :none;\r\n");
      out.write("}\r\n");
      out.write("#form {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 360px;\r\n");
      out.write("\ttop: 387px;\r\n");
      out.write("\theight: 34px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"/Bingle/jQueryAssets/autoComplete.js\" type=\r\n");
      out.write("\"text/javascript\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("\t<div class=\"img\" id=\"img\"><img src=\"img/Bingle.png\" width=\"539\" height=\"190\" alt=\"Bingle\"/></div>\r\n");
      out.write("\t<div class=\"form\" id=\"form\">\r\n");
      out.write("    <form id=\"form1\" name=\"form1\" method=\"post\" action=\"/Bingle/servlet/PostSearch\">\r\n");
      out.write("    \t<input name=\"keywards\" type=\"text\" class=\"keywards\" id=\"keywards\" value=\"\" size=\"60\" maxlength=\"76\" onkeyup=\"autoComplete.start(event)\">\r\n");
      out.write("    \t<div class=\"auto_hidden\" id=\"auto\"><!--自动完成 DIV--></div>\r\n");
      out.write("    \t&nbsp;&nbsp;\r\n");
      out.write("    \t<button type=\"submit\" class=\"submit gray tags\" name=\"submit\" id=\"submit\" value=\"Bingle\">Bingle</button>\r\n");
      out.write("    </form>\r\n");
      out.write("    <script>\r\n");
      out.write("    ");

    	String pinyinlist="";
		@SuppressWarnings("resource")
		BufferedReader br = new BufferedReader(new FileReader("/Library/Tomcat/webapps/Bingle/list/autoComplete.txt"));  
		String data = br.readLine();//一次读入一行，直到读入null为文件结束  
		while( data!=null){  
		      pinyinlist=pinyinlist+data; 
		      data = br.readLine(); //接着读下一行  
		} 
    
      out.write("\r\n");
      out.write("\tvar autoComplete=new AutoComplete('keywards','auto',[");
      out.print(pinyinlist);
      out.write("]);\r\n");
      out.write("\t</script>\r\n");
      out.write("    <script\ttype=\"text/javascript\">\r\n");
      out.write("       document.getElementById(\"submit\").onclick=function(){\r\n");
      out.write("       var kws=document.getElementById(\"keywards\").value;\r\n");
      out.write("       kws=kws.replace(/\\s+/g,\"\");\r\n");
      out.write("       if(kws==\"\"){\r\n");
      out.write("           return false;\r\n");
      out.write("         }\r\n");
      out.write("       }\r\n");
      out.write("   </script>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
